"""Fully transparent favicon ICO, generated by Python.

An ICO is binary, so it cannot carry a ``GENERATED`` text header. That is
the one allowed rule-break: the file lives under ``generated/`` (lang_audit
skips that tree) and this module is still the source of truth. Regenerate
with ``python -m art.favicon``.

The tab identity is the title ``I❤PY``. The favicon is empty so it does
not cover a letter of that mark.
"""

from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FAVICON_PATH = ROOT / "generated" / "favicon" / "favicon.ico"
SIZES: tuple[int, ...] = (16, 32)
_HEADER = 40
_DIR = 6


def _and_mask(size: int) -> bytes:
    """1-bit AND mask, all set: every pixel is transparent to old readers."""
    stride = (size + 31) // 32 * 4
    row = b"\xff" * (size // 8) + bytes(stride - size // 8)
    return row * size


def _dib(size: int) -> bytes:
    """32-bpp BMP: XOR bitmap all alpha-0, then the AND mask."""
    header = struct.pack(
        "<IiiHHIIiiII",
        _HEADER,
        size,
        size * 2,
        1,
        32,
        0,
        0,
        0,
        0,
        0,
        0,
    )
    xor = bytes(size * size * 4)
    return header + xor + _and_mask(size)


def ico_bytes(sizes: tuple[int, ...] = SIZES) -> bytes:
    """Assemble a Windows ICO whose every pixel is fully transparent."""
    if not sizes:
        msg = "ICO needs at least one size"
        raise ValueError(msg)
    frames = [_dib(size) for size in sizes]
    offset = _DIR + 16 * len(sizes)
    parts = [struct.pack("<HHH", 0, 1, len(sizes))]
    for size, frame in zip(sizes, frames, strict=True):
        width = 0 if size >= 256 else size
        parts.append(struct.pack("<BBBBHHII", width, width, 0, 0, 1, 32, len(frame), offset))
        offset += len(frame)
    parts.extend(frames)
    return b"".join(parts)


def write(path: Path | None = None) -> Path:
    """Write the ICO and return the path."""
    target = FAVICON_PATH if path is None else path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(ico_bytes())
    return target


def main() -> Path:
    """CLI entry: regenerate ``generated/favicon/favicon.ico``."""
    path = write()
    print(f"wrote {path}")
    return path


if __name__ == "__main__":
    main()
