"""The I ❤ PY wordmark, generated by Python.

The layout follows the original mark: "I" and the heart on the top row,
"PY" on the bottom row. The glyph path data is owned here and the SVG
is assembled at runtime, so the page never ships a hand-authored SVG
file.

The reference export this design came from carried an Anthropic C2PA
content-credentials manifest (``xmlns:c2pa`` + ``<c2pa:manifest>``).
That third-party provenance blob is deliberately not part of this
output - the SVG this module writes is exactly the mark and nothing
else.
"""

from __future__ import annotations

from dataclasses import dataclass

VIEW_BOX = "0 0 1254 1254"


@dataclass(frozen=True)
class Glyph:
    """One glyph of the wordmark: path data, fill colour, placement."""

    d: str
    fill: str
    x: int
    y: int


HEART = Glyph(
    d="M0,0 L32,0 L55,4 L76,11 L92,19 L103,26 L113,34 L123,43 L133,55 L143,71 L150,87 "
    "L155,104 L158,122 L158,163 L154,185 L148,206 L140,226 L129,246 L119,261 L109,274 "
    "L100,285 L88,299 L57,330 L49,337 L35,349 L19,362 L-1,377 L-21,391 L-47,408 L-75,425 "
    "L-96,437 L-114,447 L-122,450 L-133,450 L-149,442 L-167,432 L-193,416 L-223,396 "
    "L-240,384 L-253,374 L-267,363 L-280,352 L-290,343 L-300,334 L-328,306 L-337,295 "
    "L-347,283 L-357,269 L-367,254 L-381,227 L-386,216 L-392,197 L-396,180 L-398,166 "
    "L-398,137 L-395,116 L-389,96 L-381,79 L-371,63 L-359,49 L-348,38 L-335,28 L-320,19 "
    "L-301,10 L-282,4 L-272,2 L-262,1 L-228,1 L-212,4 L-197,8 L-179,16 L-165,25 L-154,34 "
    "L-142,46 L-130,63 L-120,80 L-112,67 L-100,51 L-86,37 L-73,27 L-60,19 L-44,11 L-23,4 "
    "L-14,2 Z",
    fill="#EE1C25",
    x=887,
    y=181,
)

LETTER_P = Glyph(
    d="M0,0 L25,0 L46,1 L121,1 L155,0 L217,0 L245,2 L273,7 L289,12 L305,19 L316,25 "
    "L328,34 L339,45 L349,60 L355,73 L360,91 L362,106 L362,145 L358,166 L350,186 "
    "L341,200 L330,212 L322,219 L308,228 L293,235 L275,241 L258,245 L237,248 L211,250 "
    "L130,250 L131,312 L134,325 L138,331 L144,334 L150,335 L177,336 L190,340 L197,344 "
    "L202,349 L206,355 L208,361 L208,376 L204,387 L197,396 L188,401 L178,404 L46,404 "
    "L23,405 L-4,405 L-15,402 L-21,398 L-29,389 L-33,377 L-33,361 L-29,351 L-22,343 "
    "L-10,337 L-6,336 L13,335 L22,332 L26,326 L29,315 L29,94 L25,83 L19,78 L14,76 "
    "L-2,75 L-13,71 L-21,65 L-27,55 L-30,45 L-30,31 L-26,19 L-20,11 L-13,5 L-4,1 Z",
    fill="#000000",
    x=232,
    y=665,
)

LETTER_Y = Glyph(
    d="M0,0 L26,0 L39,1 L145,1 L157,5 L166,12 L172,22 L174,28 L174,48 L170,58 L164,66 "
    "L156,71 L150,74 L132,76 L129,78 L130,85 L143,104 L153,119 L163,134 L178,157 "
    "L188,173 L190,173 L202,156 L215,138 L228,120 L241,102 L253,85 L254,78 L251,76 "
    "L239,75 L227,70 L220,63 L215,54 L213,45 L213,29 L217,18 L224,9 L234,3 L243,0 "
    "L272,0 L288,1 L393,1 L407,5 L416,11 L422,19 L426,29 L426,45 L423,55 L416,64 "
    "L407,70 L399,73 L388,75 L374,76 L367,78 L359,83 L347,98 L337,112 L323,130 L307,151 "
    "L295,167 L279,188 L265,207 L253,223 L238,243 L238,312 L240,322 L244,329 L251,333 "
    "L254,334 L275,335 L287,337 L297,341 L305,348 L308,352 L311,358 L311,378 L305,390 "
    "L301,395 L293,400 L278,404 L88,404 L77,400 L68,392 L63,382 L62,378 L62,360 L66,351 "
    "L73,343 L84,337 L93,335 L119,334 L127,330 L132,322 L134,312 L134,245 L123,229 "
    "L110,211 L97,193 L85,176 L73,159 L59,139 L48,123 L32,100 L22,85 L14,78 L7,76 L-8,74 "
    "L-17,69 L-22,65 L-27,57 L-30,48 L-30,29 L-27,20 L-21,11 L-14,5 L-4,1 Z",
    fill="#000000",
    x=628,
    y=665,
)

LETTER_I = Glyph(
    d="M0,0 L32,0 L175,1 L187,5 L195,11 L201,19 L204,26 L205,33 L205,46 L202,56 L196,64 "
    "L189,70 L179,74 L168,76 L152,77 L146,80 L141,86 L138,97 L138,334 L140,347 L143,353 "
    "L148,357 L154,359 L173,360 L189,364 L197,369 L202,374 L207,384 L208,388 L208,402 "
    "L201,416 L194,423 L183,428 L179,429 L41,429 L23,430 L-9,430 L-20,426 L-29,419 "
    "L-34,411 L-36,404 L-36,384 L-31,374 L-24,367 L-18,363 L-7,360 L15,359 L22,356 "
    "L27,350 L30,340 L30,94 L26,84 L21,79 L15,77 L-3,76 L-14,73 L-22,69 L-29,62 L-33,54 "
    "L-35,48 L-35,29 L-30,17 L-24,10 L-14,4 L-5,1 Z",
    fill="#000000",
    x=253,
    y=187,
)

# P's counter (the hole in the bowl), painted off-white on top.
P_COUNTER = Glyph(
    d="M0,0 L48,0 L73,5 L88,13 L93,17 L101,28 L105,39 L107,49 L107,69 L103,82 L97,93 "
    "L88,103 L78,109 L64,114 L43,117 L-8,117 L-19,116 L-20,115 L-20,19 L-17,10 L-13,4 "
    "L-7,1 Z",
    fill="#FBFBFB",
    x=382,
    y=735,
)

# Document order is paint order: the counter must stay last, on top of P.
GLYPHS: tuple[Glyph, ...] = (HEART, LETTER_P, LETTER_Y, LETTER_I, P_COUNTER)
# Landing lockup hides the Glaser heart; the parametric curve overlays it.
LETTER_GLYPHS: tuple[Glyph, ...] = (LETTER_P, LETTER_Y, LETTER_I, P_COUNTER)


def _svg_from(
    glyphs: tuple[Glyph, ...],
    *,
    extra: str = "",
    counter_fill: str | None = None,
    title: str | None = None,
) -> str:
    paths = "".join(
        f'<path d="{glyph.d}" fill="'
        f'{counter_fill if counter_fill is not None and glyph is P_COUNTER else glyph.fill}"'
        f' transform="translate({glyph.x},{glyph.y})"/>'
        for glyph in glyphs
    )
    title_el = f"<title>{title}</title>" if title else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEW_BOX}"{extra}>'
        f"{title_el}{paths}</svg>"
    )


def logo_svg() -> str:
    """Assemble the wordmark as a self-contained SVG string.

    Only a ``viewBox`` is emitted (no fixed width/height) so the
    embedding page controls the rendered size with CSS.
    """
    return _svg_from(GLYPHS)


def letters_svg() -> str:
    """I and PY only — the landing overlays the parametric heart instead."""
    return _svg_from(LETTER_GLYPHS)


def nav_mark_svg() -> str:
    """40px header mark: full wordmark, Glaser heart included, P-hole is paper."""
    return _svg_from(
        GLYPHS,
        extra=' class="block" role="img" aria-label="I love PY"',
        counter_fill="var(--color-surface)",
        title="I love PY",
    )
