"""Generate the CI workflow (generated/ci/ci-pipeline.yml) from Python.

The repo is pure-Python: this YAML exists only because a Python script
writes it. The header marks it GENERATED so the language audit accepts it.

The pipeline mirrors exactly what the quality panel runs locally:
ruff format, ruff lint, mypy --strict, pytest with coverage, radon,
bandit, pip-audit, the language audit, and a real k6 load test of the
running app.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = ROOT / "generated" / "ci"

GENERATED_HEADER = (
    "# GENERATED by scripts/ci_yaml.py -- do not edit by hand."
    " Regenerate: python -m scripts.ci_yaml"
)

K6_VERSION = "v0.55.0"
LIVE_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"

# Command fragments kept short so the template lines fit the 100-char limit.
TARGETS = "app.py art panel review git_discipline explain loadtest scripts tests"
PACKAGES = (
    "nicegui hypothesis pytest pytest-cov coverage ruff mypy radon bandit pip-audit types-PyYAML"
)
INSTALL_CMD = f"python -m pip install {PACKAGES}"
RADON_PKGS = "art panel review git_discipline explain loadtest scripts"
# CI installs k6 into /tmp; this is command text, not a local tempfile. nosec B108
K6_BIN = f"/tmp/k6-{K6_VERSION}-linux-amd64/k6"  # nosec B108
K6_TARBALL = (
    f"https://github.com/loadimpact/k6/releases/download/{K6_VERSION}/"
    f"k6-{K6_VERSION}-linux-amd64.tar.gz"
)

# The exact steps the local quality stack runs (panel/telemetry.py mirrors
# these). Keeping them here as data keeps the YAML template readable.
QUALITY_STEPS: list[tuple[str, str]] = [
    ("ruff format --check", f"python -m ruff format --check {TARGETS}"),
    ("ruff lint", f"python -m ruff check {TARGETS}"),
    (
        "mypy --strict",
        "python -m mypy app.py art panel review git_discipline explain loadtest scripts",
    ),
    ("pytest with coverage", "python -m pytest -q --cov --cov-report=xml --cov-report=term"),
    (
        "radon complexity (no D/E)",
        "\n".join(
            [
                f"out=$(python -m radon cc {RADON_PKGS} -s -n D)",
                'if [ -n "$out" ]; then',
                '  echo "Functions at D/E complexity (forbidden by repo rules):"',
                '  echo "$out"',
                "  exit 1",
                "fi",
                'echo "No D/E complexity functions."',
            ]
        ),
    ),
    (
        "bandit security scan",
        "python -m bandit -r art panel review git_discipline explain loadtest scripts",
    ),
    ("pip-audit dependency scan", "python -m pip_audit"),
    ("pure-Python language audit", "python -m scripts.lang_audit"),
]


def _quality_step(name: str, run: str) -> str:
    """One workflow step; `|` so multi-line gate commands keep their newlines."""
    body = "\n".join("          " + line for line in run.splitlines())
    return f"      - name: {name}\n        run: |\n{body}"


def build_yaml() -> str:
    """Assemble the full workflow file as text."""
    quality = "\n".join(_quality_step(name, run) for name, run in QUALITY_STEPS)
    return f"""{GENERATED_HEADER}
# Pipeline for i-love-python (Otrobonita AI Labs).
name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: quality (ruff, mypy, pytest, radon, bandit, audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install
        run: |
          python -m pip install --upgrade pip
          {INSTALL_CMD}
{quality}
      - name: upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

  load-test:
    name: k6 load test against the running app
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install
        run: |
          python -m pip install --upgrade pip
          python -m pip install nicegui
      - name: boot the app
        run: |
          nohup python app.py > app.log 2>&1 &
          for i in $(seq 1 30); do
            if curl -sf http://127.0.0.1:8321/api/health > /dev/null; then break; fi
            sleep 1
          done
          curl -sf http://127.0.0.1:8321/api/health
      - name: generate k6 script from the Python spec
        run: python -m loadtest.generate generated/k6/load.js
      - name: install k6
        run: |
          curl -sSfL {K6_TARBALL} | tar -xz -C /tmp
          chmod +x {K6_BIN}
          {K6_BIN} version
      - name: run k6
        run: {K6_BIN} run generated/k6/load.js
"""


def write_yaml() -> tuple[Path, Path]:
    """Write the generated YAML and install the live .github/workflows copy.

    Same pattern as install_hooks.py: the tracked artifact and the live copy
    are both written here, so regenerating can never let them drift.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    text = build_yaml()
    out = GENERATED_DIR / "ci-pipeline.yml"
    out.write_text(text, encoding="utf-8")
    LIVE_WORKFLOW.parent.mkdir(parents=True, exist_ok=True)
    LIVE_WORKFLOW.write_text(text, encoding="utf-8")
    _validate(text)
    return out, LIVE_WORKFLOW


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(f"generated CI YAML failed validation: {message}")


def _validate(text: str) -> None:
    """Parse the generated YAML (when a parser exists) and sanity-check it."""
    try:
        import yaml
    except ImportError:
        return  # no parser available; the file is still generated deterministically
    doc = yaml.safe_load(text)
    _check(doc.get("name") == "ci", "workflow name must be 'ci'")
    _check(set(doc.get("jobs", {})) == {"quality", "load-test"}, "jobs must be quality + load-test")
    quality_steps = [s.get("name", "") for s in doc["jobs"]["quality"]["steps"]]
    _check("mypy --strict" in quality_steps, "quality job must run mypy --strict")
    _check("pure-Python language audit" in quality_steps, "quality job must run the language audit")


def main() -> int:
    out, live = write_yaml()
    lines = len(out.read_text(encoding="utf-8").splitlines())
    print(f"generated {out.relative_to(ROOT)} ({lines} lines)")
    print(f"installed live workflow: {live.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
