"""Generate the git pre-commit hook from Python.

Two artifacts, both produced by this module:

* generated/hooks/pre-commit.sh -- the tracked, human-reviewable template
  (GENERATED header, so the language audit accepts it).
* .git/hooks/pre-commit -- the installed copy (LF line endings, executable),
  which lives outside the tree and therefore never breaks the pure-Python
  constraint.

The hook runs the fast part of the quality stack before every commit:
format check, lint, types, and the test suite. Anything slow (bandit,
pip-audit, radon) stays in CI and the quality panel.
"""

from __future__ import annotations

import stat
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_HOOKS = ROOT / "generated" / "hooks"
TEMPLATE_NAME = "pre-commit.sh"

HEADER = "#!/bin/sh"
GENERATED_NOTE = (
    "# GENERATED by scripts/install_hooks.py -- do not edit by hand.\n"
    "# Regenerate: python -m scripts.install_hooks\n"
)

# Fast checks only: the hook must stay under ~30s or people will --no-verify.
# Each step is (label, python-module, argv-for-the-module).
STEPS: list[tuple[str, str, list[str]]] = [
    (
        "ruff format --check",
        "ruff",
        [
            "format",
            "--check",
            "app.py",
            "art",
            "panel",
            "review",
            "git_discipline",
            "explain",
            "loadtest",
            "scripts",
            "tests",
        ],
    ),
    (
        "ruff check",
        "ruff",
        [
            "check",
            "app.py",
            "art",
            "panel",
            "review",
            "git_discipline",
            "explain",
            "loadtest",
            "scripts",
            "tests",
        ],
    ),
    (
        "mypy --strict",
        "mypy",
        [
            "app.py",
            "art",
            "panel",
            "review",
            "git_discipline",
            "explain",
            "loadtest",
            "scripts",
        ],
    ),
    # --basetemp keeps pytest's temp dirs in the repo: on Windows the user
    # temp dir can be locked (antivirus, other sessions) and pytest's end-of-
    # session cleanup then crashes the whole hook.
    ("pytest", "pytest", ["-q", "-m", "not slow", "--basetemp=.pytest-tmp"]),
]


def quote_arg(arg: str) -> str:
    """Quote an argv word for POSIX sh when it contains spaces."""
    return f'"{arg}"' if " " in arg else arg


def build_hook() -> str:
    """Assemble the sh script text (POSIX sh, LF endings)."""
    body = []
    for label, module, argv in STEPS:
        joined = " ".join(quote_arg(a) for a in argv)
        body.append(f'echo "  - {label}"')
        body.append(f'"$PY" -m {module} {joined} || exit 1')
    steps_text = "\n".join(body)
    return f"""{HEADER}
{GENERATED_NOTE}
set -u

# Resolve the repo root from the hook's location, then the venv python.
cd "$(git rev-parse --show-toplevel)" || exit 1
PY="./.venv/bin/python"
[ -x "./.venv/Scripts/python.exe" ] && PY="./.venv/Scripts/python.exe"
[ -x "$PY" ] || {{ echo "venv not found; create it: python -m venv .venv"; exit 1; }}

echo "pre-commit: i-love-python fast quality gate"
missing=""
for tool in ruff mypy pytest; do
  "$PY" -c "import $tool" >/dev/null 2>&1 || missing="$missing $tool"
done
if [ -n "$missing" ]; then
  echo "  installing missing tools:$missing"
  "$PY" -m pip install --quiet ruff mypy pytest >/dev/null
fi

status=0
{steps_text}

if [ "$status" -eq 0 ]; then
  echo "pre-commit: all fast checks passed"
fi
exit $status
"""


def _fix_line_endings(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def write_template() -> Path:
    """Write the tracked template under generated/hooks/."""
    GENERATED_HOOKS.mkdir(parents=True, exist_ok=True)
    out = GENERATED_HOOKS / TEMPLATE_NAME
    out.write_text(_fix_line_endings(build_hook()), encoding="utf-8", newline="\n")
    return out


def install() -> Path | None:
    """Copy the hook into .git/hooks/pre-commit and make it executable."""
    git_dir = ROOT / ".git"
    if not git_dir.is_dir():
        return None  # not a git checkout; nothing to install
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    target = hooks_dir / "pre-commit"
    target.write_text(_fix_line_endings(build_hook()), encoding="utf-8", newline="\n")
    target.chmod(target.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return target


def main() -> int:
    template = write_template()
    print(f"generated {template.relative_to(ROOT)}")
    target = install()
    if target is None:
        print(".git/hooks: not a git checkout, skipped installing the live hook")
    else:
        print(f"installed live hook: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
