"""Pure-Python language audit.

Enforces the repo's core rule: hand-authored *source* files must be Python.
A non-Python source file is allowed only if it was generated by Python and
carries a GENERATED marker in its header, or if it lives under generated/.

Exits non-zero when violations are found, so it can gate CI and git hooks.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Source-code extensions that are NOT Python. Config/data/doc formats (md, toml,
# yml, json, txt, ...) are intentionally not listed — they are not source.
NON_PYTHON_SOURCE_EXTS = frozenset(
    {
        ".js",
        ".mjs",
        ".cjs",
        ".ts",
        ".tsx",
        ".jsx",
        ".vue",
        ".svelte",
        ".sh",
        ".bash",
        ".zsh",
        ".ksh",
        ".ps1",
        ".psm1",
        ".bat",
        ".cmd",
        ".html",
        ".htm",
        ".css",
        ".scss",
        ".less",
        ".c",
        ".cc",
        ".cpp",
        ".cxx",
        ".h",
        ".hpp",
        ".rs",
        ".go",
        ".java",
        ".swift",
        ".kt",
        ".scala",
        ".rb",
        ".php",
        ".pl",
        ".lua",
    }
)

# A generated file must declare itself in its header.
GENERATED_MARKERS = (
    b"// GENERATED",
    b"# GENERATED",
    b"<!-- GENERATED",
    b"; GENERATED",
)

# Directories we never scan.
SKIP_DIRS = {".git", ".venv", "node_modules", ".mypy_cache", ".ruff_cache", ".pytest_cache"}

HEADER_BYTES = 256


def _is_generated(path: Path) -> bool:
    try:
        head = path.read_bytes()[:HEADER_BYTES]
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_MARKERS)


def audit(root: Path) -> list[str]:
    """Return relative paths of hand-authored non-Python source files."""
    violations: list[str] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(root).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        if "generated" in rel_parts:
            continue
        if path.suffix.lower() not in NON_PYTHON_SOURCE_EXTS:
            continue
        if _is_generated(path):
            continue
        violations.append(path.relative_to(root).as_posix())
    return violations


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    violations = audit(root)
    if violations:
        print("lang-audit: FAIL - hand-authored non-Python source found:")
        for violation in violations:
            print(f"  {violation}")
        print("Fix: generate it from Python with a GENERATED header, or place it under generated/.")
        return 1
    print("lang-audit: OK - all hand-authored source is Python.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
