"""Compile a LoadSpec into a k6 JavaScript script.

The JavaScript is an *output* of Python, never an input. The generated file
carries a GENERATED header so the pure-Python audit accepts it.

The emitted script is deliberately simple and dependency-free (only k6's
built-in http module), so `node --check` can syntax-validate it without k6.
"""

from __future__ import annotations

from pathlib import Path

from loadtest.spec import LoadSpec

GENERATED_HEADER = (
    "// GENERATED by loadtest/generate.py - do not edit. Edit loadtest/spec.py instead."
)


def _js_number(value: int | float) -> str:
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _stage(duration_s: int, target: int) -> str:
    return f"    {{ duration: '{duration_s}s', target: {target}, granularity: '1s' }}"


def compile_js(spec: LoadSpec) -> str:
    """Render the full k6 script for a spec."""
    stages: list[str] = []
    if spec.ramp_up_s > 0:
        stages.append(_stage(spec.ramp_up_s, spec.vus))
    if spec.hold_s > 0:
        stages.append(_stage(spec.hold_s, spec.vus))
    if spec.ramp_down_s > 0:
        stages.append(_stage(spec.ramp_down_s, 0))
    if not stages:
        stages.append(_stage(spec.total_s, spec.vus))
    stages_js = ",\n".join(stages)
    return (
        f"{GENERATED_HEADER}\n"
        f"// Spec: vus={spec.vus} ramp={spec.ramp_up_s}s hold={spec.hold_s}s "
        f"down={spec.ramp_down_s}s p95<{spec.p95_ms}ms err<{spec.error_rate}\n"
        "import http from 'k6/http';\n"
        "\n"
        "export const options = {\n"
        "  stages: [\n"
        f"{stages_js},\n"
        "  ],\n"
        "  thresholds: {\n"
        f"    http_req_duration: ['p(95)<{spec.p95_ms}'],\n"
        f"    http_req_failed: ['rate<{_js_number(spec.error_rate)}'],\n"
        "  },\n"
        "};\n"
        "\n"
        "export default function () {\n"
        f"  const res = http.get('{spec.target_url}', {{\n"
        "    headers: { 'User-Agent': 'i-love-python-loadtest' },\n"
        "  });\n"
        "  if (res.status !== 200) {\n"
        "    throw new Error('expected 200, got ' + res.status);\n"
        "  }\n"
        "}\n"
    )


def validate_structure(js: str, spec: LoadSpec) -> list[str]:
    """Check the compiled script has the expected shape. Returns problems."""
    problems: list[str] = []
    if not js.startswith(GENERATED_HEADER):
        problems.append("missing GENERATED header")
    if "import http from 'k6/http';" not in js:
        problems.append("missing k6 http import")
    if "export default function" not in js:
        problems.append("missing default export handler")
    if f"target: {spec.vus}" not in js:
        problems.append("vus target missing")
    if f"'{spec.target_url}'" not in js:
        problems.append("target url missing")
    if f"p(95)<{spec.p95_ms}" not in js:
        problems.append("p95 threshold missing")
    if f"rate<{_js_number(spec.error_rate)}" not in js:
        problems.append("error-rate threshold missing")
    if js.count("{") != js.count("}"):
        problems.append("unbalanced braces")
    if js.count("(") != js.count(")"):
        problems.append("unbalanced parens")
    return problems


def write_js(spec: LoadSpec, out: Path) -> Path:
    """Compile and write the script, failing hard if the shape is wrong."""
    js = compile_js(spec)
    problems = validate_structure(js, spec)
    if problems:
        raise ValueError(f"compiled k6 script failed validation: {'; '.join(problems)}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(js, encoding="utf-8")
    return out
