"""Unit tests for the pure-Python language audit."""

from pathlib import Path

from scripts.lang_audit import audit


def test_flags_plain_javascript(tmp_path: Path) -> None:
    (tmp_path / "app.js").write_text("console.log('hi');", encoding="utf-8")
    assert audit(tmp_path) == ["app.js"]


def test_allows_generated_javascript(tmp_path: Path) -> None:
    (tmp_path / "gen.js").write_text("// GENERATED by Python - do not edit.\n", encoding="utf-8")
    assert audit(tmp_path) == []


def test_allows_generated_directory(tmp_path: Path) -> None:
    (tmp_path / "generated" / "k6").mkdir(parents=True)
    (tmp_path / "generated" / "k6" / "load_test.js").write_text(
        "import http from 'k6/http';", encoding="utf-8"
    )
    assert audit(tmp_path) == []


def test_allows_python_and_docs(tmp_path: Path) -> None:
    (tmp_path / "ok.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / "notes.md").write_text("# notes\n", encoding="utf-8")
    (tmp_path / "conf.toml").write_text("[x]\n", encoding="utf-8")
    assert audit(tmp_path) == []


def test_flags_shell_scripts(tmp_path: Path) -> None:
    (tmp_path / "run.sh").write_text("#!/bin/sh\necho hi\n", encoding="utf-8")
    assert audit(tmp_path) == ["run.sh"]


def test_skips_venv_and_git(tmp_path: Path) -> None:
    (tmp_path / ".venv").mkdir()
    (tmp_path / ".venv" / "bad.js").write_text("x", encoding="utf-8")
    (tmp_path / ".git").mkdir()
    (tmp_path / ".git" / "bad.js").write_text("x", encoding="utf-8")
    assert audit(tmp_path) == []
