"""Tests for scripts/ci_yaml.py (generated CI pipeline)."""

from __future__ import annotations

import scripts.ci_yaml as ci_yaml


def test_yaml_has_generated_header() -> None:
    text = ci_yaml.build_yaml()
    first_line = text.splitlines()[0]
    assert first_line.startswith("# GENERATED by scripts/ci_yaml.py")


def test_yaml_parses_and_has_both_jobs() -> None:
    import yaml

    doc = yaml.safe_load(ci_yaml.build_yaml())
    assert doc["name"] == "ci"
    assert set(doc["jobs"]) == {"quality", "load-test"}
    assert doc["jobs"]["load-test"]["needs"] == "quality"


def test_quality_job_covers_the_full_local_stack() -> None:
    import yaml

    doc = yaml.safe_load(ci_yaml.build_yaml())
    all_steps = doc["jobs"]["quality"]["steps"]
    # Every step is either a named run-step or a `uses:` step.
    assert all(s.get("name") or s.get("uses") for s in all_steps)
    steps = [s.get("name", "") for s in all_steps]
    for expected in (
        "ruff format --check",
        "ruff lint",
        "mypy --strict",
        "pytest with coverage",
        "bandit security scan",
        "pip-audit dependency scan",
        "pure-Python language audit",
    ):
        assert expected in steps, f"missing step: {expected}"


def test_load_test_job_boots_app_and_runs_k6() -> None:
    import yaml

    doc = yaml.safe_load(ci_yaml.build_yaml())
    steps = {s.get("name", ""): s.get("run", "") for s in doc["jobs"]["load-test"]["steps"]}
    assert "api/health" in steps["boot the app"]
    assert "loadtest.generate" in steps["generate k6 script from the Python spec"]
    assert "k6 run generated/k6/load.js" in steps["run k6"]


def test_every_quality_step_uses_the_project_python() -> None:
    text = ci_yaml.build_yaml()
    # No bare 'pytest'/'ruff' invocations that would skip the venv.
    import re

    allowed_prefixes = (
        "python -m ruff",
        "python -m mypy",
        "python -m pytest",
        "python -m radon",
        "python -m bandit",
        "python -m pip_audit",
        "python -m pip",
        "python -m scripts.lang_audit",
        "python -m loadtest.generate",
        "/tmp/k6",
    )
    runs = re.findall(r"^\s+run: (.+)$", text, flags=re.MULTILINE)
    for run in runs:
        if run in ("|", ">", ">-"):
            continue  # block scalar; its lines are plain shell, checked by other tests
        if run.startswith(allowed_prefixes):
            continue
        raise AssertionError(f"unexpected run command: {run}")
