"""Unit tests for the review personas."""

from review.personas import TONE_BLOCK, TONE_CAUTION, TONE_OK, review_diff

GOOD_PYTHON_DIFF = """diff --git a/art/heart.py b/art/heart.py
--- a/art/heart.py
+++ b/art/heart.py
@@ -1 +1 @@
-    y = 1.0
+    y = 2.0
diff --git a/tests/unit/test_heart.py b/tests/unit/test_heart.py
--- a/tests/unit/test_heart.py
+++ b/tests/unit/test_heart.py
@@ -1 +1 @@
-    assert 1
+    assert 2
"""

DIFF_WITH_EVAL = """diff --git a/bad.py b/bad.py
new file mode 100644
--- /dev/null
+++ b/bad.py
@@ -0,0 +1 @@
+result = eval(user_input)
"""

NON_PYTHON_NO_MARKER = """diff --git a/legacy/app.js b/legacy/app.js
new file mode 100644
--- /dev/null
+++ b/legacy/app.js
@@ -0,0 +1 @@
+console.log('hello');
"""

NON_PYTHON_GENERATED = """diff --git a/generated/k6/load_test.js b/generated/k6/load_test.js
new file mode 100644
--- /dev/null
+++ b/generated/k6/load_test.js
@@ -0,0 +2 @@
+// GENERATED by loadtest/generate.py - do not edit.
+import http from 'k6/http';
"""


def test_good_diff_gets_full_approval() -> None:
    review = review_diff(GOOD_PYTHON_DIFF)
    assert len(review.verdicts) == 3
    assert all(v.tone == TONE_OK for v in review.verdicts)
    assert review.consensus_tone == TONE_OK


def test_eval_is_a_block_for_skeptic() -> None:
    review = review_diff(DIFF_WITH_EVAL)
    skeptic = next(v for v in review.verdicts if v.persona == "Skeptic")
    assert skeptic.tone == TONE_BLOCK
    assert review.consensus_tone == TONE_BLOCK


def test_unmarked_non_python_file_trips_purist() -> None:
    review = review_diff(NON_PYTHON_NO_MARKER)
    purist = next(v for v in review.verdicts if v.persona == "Purist")
    assert purist.tone == TONE_CAUTION


def test_generated_non_python_file_is_accepted() -> None:
    review = review_diff(NON_PYTHON_GENERATED)
    purist = next(v for v in review.verdicts if v.persona == "Purist")
    assert purist.tone == TONE_OK
    assert review.consensus_tone == TONE_OK


def test_review_is_deterministic() -> None:
    first = review_diff(GOOD_PYTHON_DIFF)
    second = review_diff(GOOD_PYTHON_DIFF)
    assert first == second
