"""Tests for scripts/install_hooks.py (generated pre-commit hook)."""

from __future__ import annotations

import scripts.install_hooks as hooks


def test_hook_has_sh_shebang_and_generated_note() -> None:
    text = hooks.build_hook()
    assert text.splitlines()[0] == "#!/bin/sh"
    assert "GENERATED by scripts/install_hooks.py" in text


def test_hook_covers_the_fast_quality_gate() -> None:
    text = hooks.build_hook()
    for label in ("ruff format --check", "ruff check", "mypy --strict", "pytest"):
        assert f"- {label}" in text, f"missing step: {label}"


def test_hook_uses_venv_python_for_every_step() -> None:
    text = hooks.build_hook()
    for label, module, argv in hooks.STEPS:
        joined = " ".join(hooks.quote_arg(a) for a in argv)
        expected = f'"$PY" -m {module} {joined} || exit 1'
        assert expected in text, f"step not wired via venv python: {label}"


def test_hook_fails_fast_on_first_error() -> None:
    text = hooks.build_hook()
    # Every quality step aborts the hook with a non-zero exit.
    step_lines = [
        line
        for line in text.splitlines()
        if '"$PY" -m' in line and line.rstrip().endswith("|| exit 1")
    ]
    assert len(step_lines) == len(hooks.STEPS)


def test_line_endings_are_forced_to_lf() -> None:
    text = hooks._fix_line_endings("a\r\nb\rc\r")
    assert text == "a\nb\nc\n"


def test_template_write_roundtrip(tmp_path: object) -> None:
    import pathlib

    # Write through the real function but redirect the module target.
    original = hooks.GENERATED_HOOKS
    hooks.GENERATED_HOOKS = pathlib.Path(str(tmp_path))
    try:
        out = hooks.write_template()
    finally:
        hooks.GENERATED_HOOKS = original
    assert out.read_text(encoding="utf-8").startswith("#!/bin/sh")
