"""Unit tests for scripts/wiring_diagram.py (the diagram generator)."""

from __future__ import annotations

from pathlib import Path

import scripts.wiring_diagram as diagram


def test_html_has_generated_header_and_structure() -> None:
    html = diagram.build_html()
    assert html.startswith("<!-- GENERATED by scripts/wiring_diagram.py")
    assert "<!doctype html>" in html
    assert "<title>I ♥ PY Wiring Diagram</title>" in html
    assert "</html>" in html


def test_html_covers_all_five_tabs_and_the_generation_loop() -> None:
    html = diagram.build_html()
    for token in (
        "panel/render.py",
        "review/render.py",
        "explain/render.py",
        "git_discipline/render.py",
        "loadtest/render.py",
        "scripts/lang_audit.py",
        "scripts/ci_yaml.py",
        "scripts/install_hooks.py",
        "generated/k6/load.js",
        ".github/workflows/ci.yml",
    ):
        assert token in html


def test_html_is_self_contained_markup() -> None:
    html = diagram.build_html()
    assert "<script" not in html  # static page: no runtime JS of its own
    assert "<style>" in html


def test_write_html_emits_a_readable_document(tmp_path: Path) -> None:
    out = tmp_path / "wiring-diagram.html"
    out.write_text(diagram.build_html(), encoding="utf-8")
    text = out.read_text(encoding="utf-8")
    assert "GENERATED" in text.splitlines()[0]
    assert len(text.splitlines()) > 500
