"""Unit tests for art/standalone_lab.py (the downloadable script generator)."""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

import art.standalone_lab as standalone


def test_script_has_generated_header() -> None:
    script = standalone.build_script()
    assert script.startswith("# GENERATED by art/standalone_lab.py")
    assert "python -m art.standalone_lab" in script


def test_script_is_valid_python() -> None:
    # It has to actually run for someone who downloads it -- parse, don't guess.
    ast.parse(standalone.build_script())


def test_script_carries_the_same_formula_as_the_app() -> None:
    script = standalone.build_script()
    assert "16.0 * np.sin(t) ** 3" in script
    assert "13.0 * np.cos(t)" in script


def test_script_has_the_two_sliders() -> None:
    script = standalone.build_script()
    assert 'Slider(ax_t, "t"' in script
    assert 'Slider(ax_n, "samples"' in script


def test_write_script_emits_a_readable_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(standalone, "GENERATED_DIR", tmp_path)
    out = standalone.write_script()
    assert out == tmp_path / "heart_curve.py"
    text = out.read_text(encoding="utf-8")
    assert "GENERATED" in text.splitlines()[0]
    assert len(text.splitlines()) > 20
